### ISSUE TITLE
让人困惑的配置

### ISSUE THREAD

**Issue by boot-vue** [MyCATApache/Mycat2#301]
```yml
cluster: #集群,数据源选择器,既可以mycat自行检查数据源可用也可以通过mycat提供的外部接口设置设置数据源可用信息影响如何使用数据源
  close: true #关闭集群心跳,此时集群认为所有数据源都是可用的,可以通过mycat提供的外部接口设置数据源可用信息达到相同效果
  clusters: [
  {name: repli ,
   replicaType: SINGLE_NODE , # SINGLE_NODE:单一节点 ,MASTER_SLAVE:普通主从 GARELA_CLUSTER:garela cluster
   switchType: NOT_SWITCH , #NOT_SWITCH:不进行主从切换,SWITCH:进行主从切换
   readBalanceType: BALANCE_ALL  , #对于查询请求的负载均衡类型
   readBalanceName: BalanceRoundRobin , #对于查询请求的负载均衡类型
   writeBalanceName: BalanceRoundRobin ,  #对于修改请求的负载均衡类型
   masters:[defaultDs], #主节点列表
   replicas:[defaultDs2],#从节点列表
   heartbeat:{maxRetry: 3, #心跳重试次数
              minSwitchTimeInterval: 12000 , #最小主从切换间隔
              heartbeatTimeout: 12000 , #心跳超时值,毫秒
              slaveThreshold: 0 , # mysql binlog延迟值
              reuqestType: 'mysql' #进行心跳的方式,mysql或者jdbc两种
   }}
  ]
  timer: {initialDelay: 1000, period: 5, timeUnit: SECONDS} #心跳定时器
```

## 只有GARELA_CLUSTER能在masters属性配置多个数据源的名字

---

1.  examole里边masters也都写的多个datasource呀??
2.  这里的masters  replicas指的是什么?  单纯的表示主库与从库吗?

假如 逻辑库A里的  逻辑表 a  ,  数据切分存储在 真实的X  Y  Z 3个数据库各自的 a表中,   每个真实的X Y Z  数据库都各自有1个 从库(x y z) .    这里的masters与replicas应该都填啥??  不太明白
