### ISSUE TITLE
查询性能疑问

### ISSUE THREAD

**Issue by leeey111** [MyCATApache/Mycat2#545]
main分支最新代码本地启动，使用客户端根据主键(也是分片键)查询一条记录，耗时达到1、200百毫秒，有时能飙到700多毫秒，我想问下，这是正常的吗？还是说我哪里的使用姿势不对？麻烦大佬解答一下，先谢谢了🙇‍

#### 表结构
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| order_id   | bigint(20)  | NO   | PRI | NULL    | auto_increment |
| user_id    | int(11)     | NO   |     | NULL    |                |
| address_id | bigint(20)  | NO   |     | NULL    |                |
| status     | varchar(50) | YES  |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+
#### 分片配置
```yaml
{
   "customTables": {},
   "globalTables": {},
   "normalTables": {},
   "schemaName": "test",
   "shadingTables": {
      "t_order": {
         "function": {
            "properties": {
               "dbNum": "2",
               "tableNum": "2",
               "tableMethod": "mod_hash(order_id)",
               "storeNum": 2,
               "dbMethod": "mod_hash(user_id)",
               "mappingFormat": "c0/demo_ds_${dbIndex}/t_order_${tableIndex}"
            }
         }
      }
   }
}
```
### server.json
无修改，使用的是默认配置

### SQL及执行计划
```sql
select * from t_order where order_id = ?;
```

```java
MycatView(distribution=[[test.t_order]], conditions=[=($0, CAST(?0):BIGINT NOT NULL)])
Each(targetName=c0, sql=SELECT * FROM demo_ds_0.t_order_0 WHERE (`order_id` = ?) union all SELECT * FROM demo_ds_1.t_order_0 WHERE (`order_id` = ?))
```
